# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 15:38
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='书籍名称')),
                ('press', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='书籍版本')),
                ('price', models.FloatField(max_length=100, verbose_name='书籍价格')),
                ('buyoutprice', models.FloatField(blank=True, default=0, null=True, verbose_name='一口价')),
                ('ship_free', models.BooleanField(default=True, verbose_name='是否承担运费')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books/images/', verbose_name='书籍图片')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='书籍描述信息')),
                ('nums', models.IntegerField(default=0, verbose_name='书籍数量')),
                ('revoke', models.DateField(default=datetime.datetime(2018, 1, 17, 15, 38, 27, 934931), verbose_name='下架时间')),
                ('status', models.IntegerField(choices=[(1, '书城'), (2, '征书墙'), (3, '竞拍'), (4, '下架')], default=1, verbose_name='书籍状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
    ]
