# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='revoke',
            field=models.DateField(default=datetime.datetime(2018, 1, 25, 20, 43, 28, 896347), verbose_name='下架时间'),
        ),
    ]
