# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180207_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='revoke',
            field=models.DateField(default=datetime.datetime(2018, 2, 10, 6, 38, 33, 340597), verbose_name='下架时间'),
        ),
    ]
