# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180123_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/images/', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '书籍图片',
                'verbose_name': '书籍图片',
            },
        ),
        migrations.AlterField(
            model_name='books',
            name='revoke',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 18, 52, 6, 958022), verbose_name='下架时间'),
        ),
        migrations.AddField(
            model_name='booksimage',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.Books', verbose_name='书籍'),
        ),
    ]
